FROM derekadair/python-2.7

WORKDIR /app
RUN virtualenv /env

# Required for pscopg2
RUN DEBIAN_FRONTEND=noninteractive && \
	apt-get update -y && \
	apt-get install -y libpq-dev

ADD . /app

# Install app requirements
ADD requirements.txt /app/requirements.txt
RUN /env/bin/pip install -r requirements.txt

ENV AWS_CLIENT_SECRET_KEY REPLACE_ME
ENV AWS_CLIENT_PUBLIC_KEY REPLACE_ME
ENV AWS_SERVER_PUBLIC_KEY REPLACE_ME
ENV AWS_SERVER_SECRET_KEY REPLACE_ME
ENV AWS_EXPECTED_BUCKET adairsoftware-fineuploadertest

ENTRYPOINT ["/env/bin/python", "manage.py"]
CMD ["runserver", "0.0.0.0:8080"]
